@baseUrl = http://localhost:8080

###
POST {{baseUrl}}/api/v1/produtos
Content-Type: application/json

{
    "nome": "Produto1",
    "preco": 25.5
}

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "username2",
    "password": "12345678"
}

###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "username2",
    "password": "$2a$10$grhNofVA.fHk6XfU4qdfSuH8f2/7yWH0gbyVIc1eyh/NIgl0Bqehe"
}

###
@authToken = {{login.response.body.token}}
GET {{baseUrl}}/api/v1/produtos
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/api/v1/produtos/1

###
DELETE {{baseUrl}}/api/v1/produtos/3
